# Generated by Django 2.0.1 on 2018-01-08 09:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='Name')),
                ('price', models.IntegerField(blank=True, default=0, verbose_name='Price')),
                ('bar_code', models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='Bar Code')),
                ('stock', models.IntegerField(blank=True, default=0, verbose_name='Stock')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('category', models.ManyToManyField(to='inventory.Category')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
    ]
