# Generated by Django 2.0.1 on 2018-01-22 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20180115_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.ManyToManyField(blank=True, to='inventory.Category'),
        ),
    ]
