# Generated by Django 2.0.1 on 2018-01-30 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_paymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paymentmethod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sales.PaymentMethod'),
        ),
    ]
